name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 25
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        java-version: "${{ matrix.java }}"
        distribution: temurin
    - uses: coursier/cache-action@v8
    - uses: sbt/setup-sbt@v1
    - run: sbt
           -v
           --server
           -J-Xmx6G
           scalafmtSbtCheck
           scalafmtCheckAll
           Test/compile
           test
